[2019-09-09 06:27:37,649] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: s3_dag_test.upload_file_to_s3 2019-01-01T00:00:00+00:00 [queued]>
[2019-09-09 06:27:37,655] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: s3_dag_test.upload_file_to_s3 2019-01-01T00:00:00+00:00 [queued]>
[2019-09-09 06:27:37,655] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-09-09 06:27:37,655] {taskinstance.py:839} INFO - Starting attempt 3 of 3
[2019-09-09 06:27:37,655] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-09-09 06:27:37,675] {taskinstance.py:859} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2019-01-01T00:00:00+00:00
[2019-09-09 06:27:37,676] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 's3_dag_test', 'upload_file_to_s3', '2019-01-01T00:00:00+00:00', '--job_id', '7', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/upload_file_to_s3.py', '--cfg_path', '/tmp/tmp67v3f1uy']
[2019-09-09 06:27:38,058] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3 [2019-09-09 06:27:38,057] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-09-09 06:27:38,320] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3 [2019-09-09 06:27:38,320] {dagbag.py:90} INFO - Filling up the DagBag from /home/jennie/airflow/dags/upload_file_to_s3.py
[2019-09-09 06:27:38,321] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3 /home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/utils/helpers.py:423: DeprecationWarning: Importing 'DummyOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2019-09-09 06:27:38,321] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   DeprecationWarning)
[2019-09-09 06:27:38,322] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3 /home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/utils/helpers.py:423: DeprecationWarning: Importing 'PythonOperator' directly from 'airflow.operators' has been deprecated. Please import from 'airflow.operators.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
[2019-09-09 06:27:38,322] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   DeprecationWarning)
[2019-09-09 06:27:38,371] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3 [2019-09-09 06:27:38,371] {credentials.py:1182} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-09-09 06:27:38,403] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3 [2019-09-09 06:27:38,403] {cli.py:516} INFO - Running <TaskInstance: s3_dag_test.upload_file_to_s3 2019-01-01T00:00:00+00:00 [running]> on host Jennie-ubuntu-GX501VSK
[2019-09-09 06:27:38,408] {python_operator.py:105} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=s3_dag_test
AIRFLOW_CTX_TASK_ID=upload_file_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2019-09-09 06:27:38,419] {logging_mixin.py:95} INFO - [[34m2019-09-09 06:27:38,419[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-09 06:27:39,610] {taskinstance.py:1051} ERROR - The key titanic-train.csv already exists.
Traceback (most recent call last):
  File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/jennie/airflow/dags/upload_file_to_s3.py", line 30, in upload_file_to_s3_with_hook
    hook.load_file(filename, key, bucket_name)
  File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/hooks/S3_hook.py", line 343, in load_file
    raise ValueError("The key {key} already exists.".format(key=key))
ValueError: The key titanic-train.csv already exists.
[2019-09-09 06:27:39,611] {taskinstance.py:1082} INFO - Marking task as FAILED.
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3 Traceback (most recent call last):
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/bin/airflow", line 32, in <module>
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     args.func(args)
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     return f(*args, **kwargs)
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     _run(args, dag, ti)
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     pool=args.pool,
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-09-09 06:27:39,646] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     return func(*args, **kwargs)
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     result = task_copy.execute(context=context)
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     return_value = self.execute_callable()
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     return self.python_callable(*self.op_args, **self.op_kwargs)
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/airflow/dags/upload_file_to_s3.py", line 30, in upload_file_to_s3_with_hook
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     hook.load_file(filename, key, bucket_name)
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3   File "/home/jennie/workspace/airflow_venv/lib/python3.7/site-packages/airflow/hooks/S3_hook.py", line 343, in load_file
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3     raise ValueError("The key {key} already exists.".format(key=key))
[2019-09-09 06:27:39,647] {base_task_runner.py:115} INFO - Job 7: Subtask upload_file_to_s3 ValueError: The key titanic-train.csv already exists.
[2019-09-09 06:27:42,655] {logging_mixin.py:95} INFO - [[34m2019-09-09 06:27:42,654[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
